# bash completion for `gh {{.Ext}}`, generated by `gh {{.Ext}} completion bash`.
#
# gh completes the names of installed extensions but not what follows them
# (cli/cli#5309). This wraps gh's own completer: when the second word is
# `{{.Ext}}`, the request is re-routed to `gh {{.Ext}} __complete ...` so
# cobra answers with the extension's commands and flags. gh's completer
# still handles the results, so nothing about its behaviour is duplicated.

__gh_ext_{{.Ident}}_exec() { gh {{.Ext}} "$@"; }

__gh_ext_{{.Ident}}_install() {
    # Already wrapped (this file was sourced twice): nothing to do.
    declare -F __gh_ext_{{.Ident}}_wrapped >/dev/null 2>&1 && return 0

    # bash-completion v2 loads gh's completer lazily on first Tab. Ask its
    # loader first, then fall back to generating the completer.
    if ! declare -F __gh_get_completion_results >/dev/null 2>&1; then
        if declare -F _completion_loader >/dev/null 2>&1; then
            _completion_loader gh >/dev/null 2>&1
        fi
    fi
    if ! declare -F __gh_get_completion_results >/dev/null 2>&1; then
        eval "$(gh completion -s bash 2>/dev/null)" || return 1
    fi
    declare -F __gh_get_completion_results >/dev/null 2>&1 || return 1

    # Chain: keep whatever the hook currently is (gh's own, or another
    # extension's wrapper) under a unique name, then put our router in front.
    eval "$(declare -f __gh_get_completion_results | sed '1s/.*/__gh_ext_{{.Ident}}_prev()/')"
    __gh_ext_{{.Ident}}_wrapped() { return 0; }

    # `words` is the caller's local; dynamic scoping lets us replace
    # `gh {{.Ext}}` with one word that runs it, so the request
    # `${words[0]} __complete ${words[@]:1}` becomes `gh {{.Ext}} __complete <rest>`.
    __gh_get_completion_results() {
        if [[ ${#words[@]} -ge 3 && "${words[1]}" == "{{.Ext}}" ]]; then
            words=(__gh_ext_{{.Ident}}_exec "${words[@]:2}")
        fi
        __gh_ext_{{.Ident}}_prev "$@"
    }
}

__gh_ext_{{.Ident}}_install
unset -f __gh_ext_{{.Ident}}_install
