# fish completion for `gh {{.Ext}}`, generated by `gh {{.Ext}} completion fish`.
#
# gh completes the names of installed extensions but not what follows them
# (cli/cli#5309). This wraps gh's own completer: when the second token is
# `{{.Ext}}`, the request goes to `gh {{.Ext}} __complete ...`. Result handling
# (directives, file completion, ordering) stays with gh's completer.
#
# Install to ~/.config/fish/conf.d/, not completions/: fish only autoloads
# completions/<name>.fish for the command <name>, and gh's own file erases
# every `gh` completion when it loads, so this must wrap after it.

function __gh_ext_{{.Ident}}_install
    # fish autoloads gh's completer on first Tab. Trigger that now (the same
    # trick gh's own script uses), then fall back to generating it.
    if not functions -q __gh_perform_completion
        complete --do-complete "gh " >/dev/null 2>&1
    end
    if not functions -q __gh_perform_completion
        gh completion -s fish 2>/dev/null | source
    end
    if not functions -q __gh_perform_completion
        return 1
    end

    # Already in the live chain that starts at gh's hook: nothing to do. A
    # free-standing marker would go stale when gh's own completion file is
    # re-sourced, which resets the hook.
    set -l f __gh_perform_completion
    while functions -q -- $f
        set -l body (functions -- $f | string collect)
        if string match -q -- '*__gh_ext_{{.Ident}}_prev*' $body
            return 0
        end
        set -l next (string match -r -- '__gh_ext_[a-z0-9_]+_prev' $body)
        if test -z "$next"; or test "$next[1]" = "$f"
            break
        end
        set f $next[1]
    end

    # Chain: keep whatever the hook currently is (gh's own, or another
    # extension's wrapper) under a unique name, then put our router in front.
    functions -e __gh_ext_{{.Ident}}_prev
    functions -c __gh_perform_completion __gh_ext_{{.Ident}}_prev

    function __gh_perform_completion
        set -l args (commandline -opc)
        if test (count $args) -lt 2; or test "$args[2]" != {{.Ext}}
            __gh_ext_{{.Ident}}_prev
            return
        end

        # Same request/print contract as cobra's fish template, with the
        # command re-routed to the extension.
        set -l lastArg (string escape -- (commandline -ct))
        set -l results (eval "GH_ACTIVE_HELP=0 gh {{.Ext}} __complete $args[3..-1] $lastArg" 2>/dev/null)
        for line in $results[-1..1]
            if test (string trim -- $line) = ""
                set results $results[1..-2]
            else
                break
            end
        end
        set -l flagPrefix (string match -r -- '-.*=' "$lastArg")
        for comp in $results[1..-2]
            printf "%s%s\n" "$flagPrefix" "$comp"
        end
        printf "%s\n" "$results[-1]"
    end
end

__gh_ext_{{.Ident}}_install
functions -e __gh_ext_{{.Ident}}_install
