# zsh completion for `gh {{.Ext}}`, generated by `gh {{.Ext}} completion zsh`.
#
# gh completes the names of installed extensions but not what follows them
# (cli/cli#5309). This wraps gh's own completer: when the second word is
# `{{.Ext}}`, the request is re-routed to `gh {{.Ext}} __complete ...` so
# cobra answers with the extension's commands and flags. gh's completer
# still handles the results, so nothing about its behaviour is duplicated.
#
# gh's completion must be available first. This loads it from fpath when it
# is a lazy autoload, and falls back to generating it.

__gh_ext_{{.Ident}}_exec() { gh {{.Ext}} "$@" }

__gh_ext_{{.Ident}}_install() {
    # Already wrapped (this file was sourced twice): nothing to do.
    (( $+functions[__gh_ext_{{.Ident}}_wrapped] )) && return 0

    # compinit registers _gh as an autoload stub whose body is the whole
    # completion file; that file only defines the real _gh when first run.
    # Load it, then hydrate it, so we wrap the completer and not the file.
    if ! (( $+functions[_gh] )) || [[ "$(functions _gh)" == *"builtin autoload"* ]]; then
        autoload -Uz +X _gh 2>/dev/null || :
    fi
    if ! (( $+functions[_gh] )) || [[ "$(functions _gh)" == *"builtin autoload"* ]]; then
        eval "$(gh completion -s zsh 2>/dev/null)" || return 1
    fi
    if [[ "$functions[_gh]" == *"_gh () {"* ]]; then
        eval "$functions[_gh]"
    fi
    (( $+functions[_gh] )) || return 1

    # Chain: keep whatever _gh currently is (gh's own, or another
    # extension's wrapper) under a unique name, then put our router in front.
    functions[__gh_ext_{{.Ident}}_prev]=$functions[_gh]
    functions[__gh_ext_{{.Ident}}_wrapped]='return 0'

    _gh() {
        if (( CURRENT >= 3 )) && [[ "${words[2]}" == "{{.Ext}}" ]]; then
            # Replace `gh {{.Ext}}` with one word that runs it, so the request
            # `${words[1]} __complete ${words[2,-1]}` becomes
            # `gh {{.Ext}} __complete <rest>`.
            words=(__gh_ext_{{.Ident}}_exec "${words[@]:2}")
            (( CURRENT-- ))
        fi
        __gh_ext_{{.Ident}}_prev "$@"
    }
    compdef _gh gh
}

__gh_ext_{{.Ident}}_install
unset -f __gh_ext_{{.Ident}}_install
